-- Grupos de usuário
--select * from auth_group
insert into auth_group (id, name) values (1, 'Admin');
insert into auth_group (id, name) values (2, 'Gestor de Área');
insert into auth_group (id, name) values (3, 'Solicitante');

-- Inicializa tabela de órgãos
-- select * from orgao
INSERT INTO orgao (nome) values ('SEXPE');
INSERT INTO orgao (nome) values ('SGIDOC');
INSERT INTO orgao (nome) values ('STVSEN');
INSERT INTO orgao (nome) values ('SEGRAF');
INSERT INTO orgao (nome) values ('IFI');
INSERT INTO orgao (nome) values ('GSHJOSE');
INSERT INTO orgao (nome) values ('GSJAGR');
INSERT INTO orgao (nome) values ('GSJVIA');
INSERT INTO orgao (nome) values ('GSOAZIZ');
INSERT INTO orgao (nome) values ('GLDPR');
INSERT INTO orgao (nome) values ('GSEAMR');
INSERT INTO orgao (nome) values ('SINFLEG');
INSERT INTO orgao (nome) values ('SLCN');
INSERT INTO orgao (nome) values ('SRSF');
INSERT INTO orgao (nome) values ('SEGP');
INSERT INTO orgao (nome) values ('SEC');
INSERT INTO orgao (nome) values ('PRDSTI');
INSERT INTO orgao (nome) values ('PRSECR');
INSERT INTO orgao (nome) values ('GSRCAL');
INSERT INTO orgao (nome) values ('GSFCOL');
INSERT INTO orgao (nome) values ('GSGFIL');
INSERT INTO orgao (nome) values ('GSICAS');
INSERT INTO orgao (nome) values ('GSLMAT');
INSERT INTO orgao (nome) values ('GSPBAU');
INSERT INTO orgao (nome) values ('GSAGUR');
INSERT INTO orgao (nome) values ('GSAMON');
INSERT INTO orgao (nome) values ('GBSGME');
INSERT INTO orgao (nome) values ('SINFRA');
INSERT INTO orgao (nome) values ('SPATR');
INSERT INTO orgao (nome) values ('QTSECR');
INSERT INTO orgao (nome) values ('GSELOB');
INSERT INTO orgao (nome) values ('GSJPIM');
INSERT INTO orgao (nome) values ('GSMSUP');
INSERT INTO orgao (nome) values ('GLDPTB');
INSERT INTO orgao (nome) values ('GLMDB');
INSERT INTO orgao (nome) values ('GSAOLI');
INSERT INTO orgao (nome) values ('GSASAND');
INSERT INTO orgao (nome) values ('GBDGER');
INSERT INTO orgao (nome) values ('BLSOCDEM');
INSERT INTO orgao (nome) values ('SLSF');
INSERT INTO orgao (nome) values ('TRSECR');
INSERT INTO orgao (nome) values ('SERERP');
INSERT INTO orgao (nome) values ('SCOM');
INSERT INTO orgao (nome) values ('GSRROCHA');
INSERT INTO orgao (nome) values ('GSSTEBET');
INSERT INTO orgao (nome) values ('ILB');
INSERT INTO orgao (nome) values ('GSJBAR');
INSERT INTO orgao (nome) values ('GSMALV');
INSERT INTO orgao (nome) values ('GSOALENC');
INSERT INTO orgao (nome) values ('GLDGCN');
INSERT INTO orgao (nome) values ('GLDGOV');
INSERT INTO orgao (nome) values ('GSAPRT');
INSERT INTO orgao (nome) values ('BLOMOD');
INSERT INTO orgao (nome) values ('SPOL');
INSERT INTO orgao (nome) values ('SAFIN');
INSERT INTO orgao (nome) values ('GSZPER');
INSERT INTO orgao (nome) values ('GSFLEX');
INSERT INTO orgao (nome) values ('GSJMAR');
INSERT INTO orgao (nome) values ('GSLMARTI');
INSERT INTO orgao (nome) values ('GLBPDC');
INSERT INTO orgao (nome) values ('SRPPM');
INSERT INTO orgao (nome) values ('GSRFER');
INSERT INTO orgao (nome) values ('GSRROD');
INSERT INTO orgao (nome) values ('GSSPET');
INSERT INTO orgao (nome) values ('GSVRAU');
INSERT INTO orgao (nome) values ('GSGCAMEL');
INSERT INTO orgao (nome) values ('GSJALB');
INSERT INTO orgao (nome) values ('GSJMEDEI');
INSERT INTO orgao (nome) values ('GSJSER');
INSERT INTO orgao (nome) values ('GSMMAL');
INSERT INTO orgao (nome) values ('GLDMAI');
INSERT INTO orgao (nome) values ('GLDPDT');
INSERT INTO orgao (nome) values ('GLPODE');
INSERT INTO orgao (nome) values ('GSBLIR');
INSERT INTO orgao (nome) values ('SGSECR');
INSERT INTO orgao (nome) values ('STRANS');
INSERT INTO orgao (nome) values ('SEADI');
INSERT INTO orgao (nome) values ('SAJS');
INSERT INTO orgao (nome) values ('GSRJUC');
INSERT INTO orgao (nome) values ('GSWPIN');
INSERT INTO orgao (nome) values ('GSFBEZER');
INSERT INTO orgao (nome) values ('GSPCHAV');
INSERT INTO orgao (nome) values ('GLDPSB');
INSERT INTO orgao (nome) values ('SGVPRE');
INSERT INTO orgao (nome) values ('SERINT');
INSERT INTO orgao (nome) values ('SECOM');
INSERT INTO orgao (nome) values ('SADCON');
INSERT INTO orgao (nome) values ('SAOP');
INSERT INTO orgao (nome) values ('GSTJER');
INSERT INTO orgao (nome) values ('GSTMOTA');
INSERT INTO orgao (nome) values ('GSVGRA');
INSERT INTO orgao (nome) values ('GSWMOR');
INSERT INTO orgao (nome) values ('GSEBRA');
INSERT INTO orgao (nome) values ('GSPAULOR');
INSERT INTO orgao (nome) values ('GLDPP');
INSERT INTO orgao (nome) values ('GSCSAN');
INSERT INTO orgao (nome) values ('GSDABEB');

-- Inicializa tabela de usuários
-- select * from auth_user
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ZABAN','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'APALBUQUERQUE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ALEXACN','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ALEXBAT','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ALEXCL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ALINELML','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'NOVELLI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANALUAO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANDREDUF','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANDRESAK','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANGELASB','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANTLIMA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ACNF','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'NOBRECES','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'HELDERM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ANTLOSSI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'BEABIZZO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'BRENOJ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'BRUNOCL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CARLOSAD','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CXAVIER','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CASSIOR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CEFAS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CELIOELI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CELSO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'CELSODIA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'NERY','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DEMETR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DENIO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DERALDOR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DERMEVAL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DPALVES','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DINAMAR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DIRCEUV','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'EDISONAL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'EDIMARF','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'EDIMATOS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ESIQUEIRA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'EGLI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ELGAM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'EWANDRO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FABRISIA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FERRAO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FELIPEOP','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FSALTO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FGOMIDE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FERDAMAS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SACHETTI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FERVEIGA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FRINCON','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FLAVIO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FRANCDIA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'BIONDO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SCARTON','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FGONDIM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FLIBERAL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'GPONCE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'HCARDOSO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'HERIVEL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'HSILV','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'HCARLOS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'INAIARA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'IFALCONI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JAQUELIN','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JOBERTO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JOELMO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'TADEUFJ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JSERGIO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JMARQUES','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JBSSOUZA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'BARIZON','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JPEDRO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JOAORIOS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'JULIAB','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LEOCR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LETIMATE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'OZELIM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUDMILAC','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUILEITE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUIZAPM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUIZCARL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUNO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MARCELIM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MMUNIZ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MREIS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MFARANI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MABEME','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'DOLHER','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MRUBEN','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MARDEN','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MCRISM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MARIAJ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'GENILSE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MMELO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'MAXPER','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'OLGASOUZ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'PATGOMES','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'PAULORSM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'PAULOVSM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'PEDRORIC','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'QUESIASF','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RAFAELCR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RAFFS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RANILTON','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RAPHAELC','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RAQUELF','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SIMPLI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RENATATP','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RENZO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RMACEDO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ROCHAEL','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'LUIZMENEZ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'RODRIGOG','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'FULGONI','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SABRINA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SMROCHA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SILVIOBM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SILVIOOS','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SYLVIOPJ','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'PORTILHO','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'SERGIOT','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'VALERIAD','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'VICENTJR','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'WALDIRBM','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'WALTERGE','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'WENISB','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ZIZELMA','','','',false, true,CURRENT_DATE);
INSERT INTO auth_user (id,password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (default,'',false,'ERICOS','','','',false, true,CURRENT_DATE);

-- Inicializa tabela de permissoes
-- select * from capacita_profile
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'BLOMOD'), (select id from auth_user where username = 'ANALUAO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'BLSOCDEM'), (select id from auth_user where username = 'HSILV'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GBDGER'), (select id from auth_user where username = 'JULIAB'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GBSGME'), (select id from auth_user where username = 'LUDMILAC'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLBPDC'), (select id from auth_user where username = 'HCARLOS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDGCN'), (select id from auth_user where username = 'IFALCONI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDGOV'), (select id from auth_user where username = 'DPALVES'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDMAI'), (select id from auth_user where username = 'MARCELIM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDPDT'), (select id from auth_user where username = 'SYLVIOPJ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDPP'), (select id from auth_user where username = 'LUILEITE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDPR'), (select id from auth_user where username = 'FERDAMAS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDPSB'), (select id from auth_user where username = 'CXAVIER'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLDPTB'), (select id from auth_user where username = 'PORTILHO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLMDB'), (select id from auth_user where username = 'TADEUFJ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GLPODE'), (select id from auth_user where username = 'ANDREDUF'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSAGUR'), (select id from auth_user where username = 'ANTLIMA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSAMON'), (select id from auth_user where username = 'ANDRESAK'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSAOLI'), (select id from auth_user where username = 'DOLHER'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSAPRT'), (select id from auth_user where username = 'NERY'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSASAND'), (select id from auth_user where username = 'ZIZELMA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSBLIR'), (select id from auth_user where username = 'DENIO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSCSAN'), (select id from auth_user where username = 'ALINELML'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSDABEB'), (select id from auth_user where username = 'ESIQUEIRA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSEAMR'), (select id from auth_user where username = 'LUNO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSEBRA'), (select id from auth_user where username = 'JSERGIO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSELOB'), (select id from auth_user where username = 'EWANDRO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSFBEZER'), (select id from auth_user where username = 'MARIAJ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSFCOL'), (select id from auth_user where username = 'JOBERTO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSFLEX'), (select id from auth_user where username = 'CARLOSAD'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSGCAMEL'), (select id from auth_user where username = 'ANTLOSSI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSGFIL'), (select id from auth_user where username = 'EDISONAL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSHJOSE'), (select id from auth_user where username = 'SIMPLI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSICAS'), (select id from auth_user where username = 'VICENTJR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJAGR'), (select id from auth_user where username = 'OLGASOUZ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJALB'), (select id from auth_user where username = 'BRENOJ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJBAR'), (select id from auth_user where username = 'LETIMATE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJMAR'), (select id from auth_user where username = 'RANILTON'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJMEDEI'), (select id from auth_user where username = 'RAFAELCR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJPIM'), (select id from auth_user where username = 'DERMEVAL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJSER'), (select id from auth_user where username = 'LEOCR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSJVIA'), (select id from auth_user where username = 'ALEXCL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSLMARTI'), (select id from auth_user where username = 'EGLI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSLMAT'), (select id from auth_user where username = 'RMACEDO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSMALV'), (select id from auth_user where username = 'MARDEN'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSMMAL'), (select id from auth_user where username = 'SERGIOT'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSMSUP'), (select id from auth_user where username = 'JBSSOUZA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSOALENC'), (select id from auth_user where username = 'SCARTON'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSOAZIZ'), (select id from auth_user where username = 'EDIMATOS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSPAULOR'), (select id from auth_user where username = 'ACNF'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSPBAU'), (select id from auth_user where username = 'PAULOVSM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSPCHAV'), (select id from auth_user where username = 'GENILSE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSRCAL'), (select id from auth_user where username = 'MMELO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSRFER'), (select id from auth_user where username = 'SILVIOOS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSRJUC'), (select id from auth_user where username = 'FERVEIGA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSRROCHA'), (select id from auth_user where username = 'FGONDIM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSRROD'), (select id from auth_user where username = 'INAIARA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSSPET'), (select id from auth_user where username = 'JMARQUES'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSSTEBET'), (select id from auth_user where username = 'JAQUELIN'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSTJER'), (select id from auth_user where username = 'FGOMIDE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSTMOTA'), (select id from auth_user where username = 'JOAORIOS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSVGRA'), (select id from auth_user where username = 'LUIZMENEZ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSVRAU'), (select id from auth_user where username = 'CELIOELI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSWMOR'), (select id from auth_user where username = 'RAQUELF'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSWPIN'), (select id from auth_user where username = 'SMROCHA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'GSZPER'), (select id from auth_user where username = 'RENZO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'IFI'), (select id from auth_user where username = 'FSALTO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'ILB'), (select id from auth_user where username = 'BIONDO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'ILB'), (select id from auth_user where username = 'HELDERM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'PRDSTI'), (select id from auth_user where username = 'ALEXBAT'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'PRDSTI'), (select id from auth_user where username = 'APALBUQUERQUE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'PRSECR'), (select id from auth_user where username = 'GPONCE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'QTSECR'), (select id from auth_user where username = 'LUIZAPM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SADCON'), (select id from auth_user where username = 'FELIPEOP'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SADCON'), (select id from auth_user where username = 'MABEME'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SADCON'), (select id from auth_user where username = 'RODRIGOG'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAFIN'), (select id from auth_user where username = 'FRINCON'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAFIN'), (select id from auth_user where username = 'MAXPER'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAFIN'), (select id from auth_user where username = 'RAFFS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAJS'), (select id from auth_user where username = 'FLAVIO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAJS'), (select id from auth_user where username = 'SILVIOBM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAOP'), (select id from auth_user where username = 'JPEDRO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAOP'), (select id from auth_user where username = 'RAPHAELC'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SAOP'), (select id from auth_user where username = 'ZABAN'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SCOM'), (select id from auth_user where username = 'BRUNOCL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SCOM'), (select id from auth_user where username = 'DIRCEUV'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEADI'), (select id from auth_user where username = 'DERALDOR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEADI'), (select id from auth_user where username = 'PATGOMES'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEADI'), (select id from auth_user where username = 'ROCHAEL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEC'), (select id from auth_user where username = 'BARIZON'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEC'), (select id from auth_user where username = 'DEMETR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SECOM'), (select id from auth_user where username = 'ANGELASB'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SECOM'), (select id from auth_user where username = 'NOVELLI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEGP'), (select id from auth_user where username = 'BEABIZZO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEGP'), (select id from auth_user where username = 'HCARDOSO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEGP'), (select id from auth_user where username = 'PAULORSM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEGRAF'), (select id from auth_user where username = 'FERRAO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEGRAF'), (select id from auth_user where username = 'LUIZCARL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SERERP'), (select id from auth_user where username = 'MMUNIZ'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SERERP'), (select id from auth_user where username = 'QUESIASF'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SERINT'), (select id from auth_user where username = 'MFARANI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SEXPE'), (select id from auth_user where username = 'CELSODIA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SGIDOC'), (select id from auth_user where username = 'DINAMAR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SGIDOC'), (select id from auth_user where username = 'WENISB'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SGSECR'), (select id from auth_user where username = 'VALERIAD'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SGVPRE'), (select id from auth_user where username = 'WALTERGE'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SINFLEG'), (select id from auth_user where username = 'FABRISIA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SINFLEG'), (select id from auth_user where username = 'FLIBERAL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SINFRA'), (select id from auth_user where username = 'JOELMO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SINFRA'), (select id from auth_user where username = 'OZELIM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SLCN'), (select id from auth_user where username = 'EDIMARF'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SLCN'), (select id from auth_user where username = 'WALDIRBM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SLSF'), (select id from auth_user where username = 'SABRINA'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SLSF'), (select id from auth_user where username = 'SACHETTI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SPATR'), (select id from auth_user where username = 'CASSIOR'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SPATR'), (select id from auth_user where username = 'FULGONI'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SPATR'), (select id from auth_user where username = 'NOBRECES'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SPOL'), (select id from auth_user where username = 'ALEXACN'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SPOL'), (select id from auth_user where username = 'PEDRORIC'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SRPPM'), (select id from auth_user where username = 'CEFAS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SRPPM'), (select id from auth_user where username = 'HERIVEL'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SRPPM'), (select id from auth_user where username = 'MCRISM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SRSF'), (select id from auth_user where username = 'CELSO'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'SRSF'), (select id from auth_user where username = 'MREIS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'STRANS'), (select id from auth_user where username = 'ELGAM'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'STRANS'), (select id from auth_user where username = 'MRUBEN'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'STVSEN'), (select id from auth_user where username = 'ERICOS'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'STVSEN'), (select id from auth_user where username = 'RENATATP'));
INSERT INTO capacita_profile  (permissao_necessidade,orgao_id,user_id) VALUES (true,(select cod_orgao from orgao where nome = 'TRSECR'), (select id from auth_user where username = 'FRANCDIA'));

-- Relação de áreas de conhecimento
-- select * FROM area_conhecimento
insert into area_conhecimento (cod_area_conhecimento, txt_descricao, ind_excluido) values (default,'COMUNICAÇÃO', false);
insert into area_conhecimento (cod_area_conhecimento, txt_descricao, ind_excluido) values (default,'DIREITO', false);
insert into area_conhecimento (cod_area_conhecimento, txt_descricao, ind_excluido) values (default,'GESTÃO', false);
insert into area_conhecimento (cod_area_conhecimento, txt_descricao, ind_excluido) values (default,'POLÍCIA E SEGURANÇA', false);
insert into area_conhecimento (cod_area_conhecimento, txt_descricao, ind_excluido) values (default,'TI', false);

select * from area_conhecimento

-- Relação de treinamentos
-- SELECT * FROM treinamento
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Capacitar servidores da Conleg com o objetivo de aperfeiçoar sua capacidade de se relacionar com jornalistas e dar em entrevistas em programas realizados', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Abordagem Policial', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Gerenciamento de Redes Sociais', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Marketing na Ciência da Informação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Design Thinking aplicado ao redesenho de processos e serviços', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('APEX', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Treinamento da Central de Serviços e Tarefas para desenvolvedores', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('TDD - Text Driven Development', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Metodologia Ágil e Scrum', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Scrum Avançado - Scrum Master e Project Owner', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Framework Apache Wicket e customizações do Senado Federal', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Hibernate básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Hibernate avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Teste automatizado de front end e servidor', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Tecnologias de front-end de aplicações web', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('AngularJS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Linux Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Power Shell', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('BPM com foco em inovação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Capacitação em Modelagem de Processos Complexos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Capacitação em Modelagem de Processos Complexos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('BPM com foco em inovação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Excel Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Construção de TRs/PBs de TI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Fase Interna do Processo Licitatório - Área Técnica', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Construção de TRs/PBs de TI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Fase Interna do Processo Licitatório - Área Técnica', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Análise de negócio e definição formal de requisitos de software', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('TDD - Test Driven Development', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Tecnologias de front-end de aplicações web', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Teste automatizado de frontend e servidor', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Django básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Django avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Vue.js em projetos Django com Django-rest-framework', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Plone 5 básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Plone 5 avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('SAPL 3.1', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Portal Modelo 3.0', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Python básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Python avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Docker', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Análise de negócio e definição formal de requisitos de software', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ITIL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Relatórios e visualização de dados com BIRT', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Docker', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Linux Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('OTRS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ZABBIX Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Kibana', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Elastic Search', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Administração e Tunning do PostgreSQL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Linux Básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Otimização de SQL Oracle', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('OTRS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ZABBIX', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gerenciamento de Projetos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ARQUIMEDES', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Projetos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Riscos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Metodologia Ágil e Scrum', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Scrum Avançado - Scrum Master e Project Owner', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('GIT', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('GALILEU - PAINÉIS VOLTADOS À SINFRA', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Projetos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Riscos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('MBA em Gestão por processos para inovação dos serviços públicos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('MBA em Gestão por processos para inovação dos serviços públicos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Capacitar servidores da Conleg nas ferramentas do SIGAD.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de SIGAD - PARA TODO O SENADO - EaD', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Treinamento em ECM para desenvolvedores', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ISO 20000', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Governança de TI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ITIL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Governança de TI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('SEDOL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Pacote Office', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCEL BÁSICO E INTERMEDIÁRIO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCEL BÁSICO E INTERMEDIÁRIO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCEL INTERMEDIÁRIO E AVANÇADO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Corel Draw', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('WORD BÁSICO, INTERMEDIÁRIO E AVANÇADO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('WORD BÁSICO, INTERMEDIÁRIO E AVANÇADO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCEL BÁSICO, INTERMEDIÁRIO E AVANÇADO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCEL BÁSICO, INTERMEDIÁRIO E AVANÇADO', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Excel', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Sigad', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Word', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Aprimorar os conhecimentos do Pacote Office do corpo técnico da Conleg, possibilitando melhor uso das ferramentas existentes e maior padronização de documentos produzidos.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso Curto - Excel Intermediário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – Excel Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – MS-Project Intermediário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Processo Legislativo', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Sistema Galileu', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Segurança da Informação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Segurança da Informação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Corel Draw', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('APEX', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('ARQUIMEDES', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Informática - Gerência RVBI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Arquimedes', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Galileu', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – QlikView Básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – QlikView intermediário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – QlikSenses Básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto – QlikSenses Intermediário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso Curto software NavisWorks', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto - software Redmine intermediário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto - software Redmine avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Arquimedes', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('LexEdit', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('GEGAB', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Escriba Básico', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Escriba Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('LEGIS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Comiss/SVE', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Comiss/SVE', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('E-Plenario', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Cotas', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso sobe AtoM', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'TI'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Desenvolvimento ou adequação de Sistema de Negócio com requisitos arquivísticos para a Gestão de Documentos - voltado para profissionais de Arquivo', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Desenvolvimento ou adequação de Sistema de Negócio com requisitos arquivísticos para a Gestão de Documentos - voltado para profissionais de TI', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Gestão de Documentos Arquivísticos - PARA TODO O SENADO (presencial)', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Desenvolvimento de coleções', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Estudo de usuário', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão e fiscalização de contratos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Projeto Básico, Termo de Referência e Pesquisa de Preços', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Controle de Distúrbios Civis', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('TEMAS CONTEMPORÂNEOS DE GÊNERO E RAÇA - CURSO A SER ABERTO PARA TODOS OS SERVIDORES DO SENADO INTERESSADOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('DEFESA PESSOAL PARA MULHERES - NOS MESMOS MOLDES DO CURSO DADO EM 2017', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Direção Defensiva e Evasiva', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCELÊNCIA NO ATENDIMENTO, COM ÊNFASE NO ATENDIMENTO A PESSOAS COM DEFICIÊNCIA', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('EXCELÊNCIA NO ATENDIMENTO, COM ÊNFASE NO ATENDIMENTO A PESSOAS COM DEFICIÊNCIA', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('TEMAS CONTEMPORÂNEOS DE GÊNERO E RAÇA - CURSO A SER ABERTO PARA TODOS OS SERVIDORES DO SENADO INTERESSADOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de Gerenciamento de Crises e Negociação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('MEDIAÇÃO DE CONFLITOS - CURSO A SER ABERTO PARA TODOS OS SERVIDORES DO SENADO INTERESSADOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('MEDIAÇÃO DE CONFLITOS - CURSO A SER ABERTO PARA TODOS OS SERVIDORES DO SENADO INTERESSADOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Imobilizações Táticas', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Mediação de Conflitos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Psicologia criminal', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('APH Tático', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Técnicas de Investigação e Entrevista', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Tiro Policial', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'POLÍCIA E SEGURANÇA'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('GRAMÁTICA DA LÍNGUA PORTUGUESA E INTERPRETAÇÃO DE TEXTOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('GRAMÁTICA DA LÍNGUA PORTUGUESA E INTERPRETAÇÃO DE TEXTOS', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Redação Oficial', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso curto - Gerenciamento de Conflitos e Reuniões', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Necessidade de aperfeiçoamento.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Projetos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gerenciamento de projetos', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Design Thinking aplicado ao redesenho de processos e serviços', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Mestrado – Governança no setor público', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Necessidade de aperfeiçoamento.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('REGULAMENTO ADMINISTRATIVO DO SENADO FEDERAL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('REGULAMENTO ADMINISTRATIVO DO SENADO FEDERAL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('PROCESSO ADMINISTRATIVO - LEI 9.784/1999', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('PROCESSO ADMINISTRATIVO - LEI 9.784/1999', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Criação de conteúdo para curso a distância de orçamento na perspectiva de Gênero e Raça, a ser disponibilizado pelo ILB/nterlegis para público interno e externo', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão de Pessoas e Equipes', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Análise transacional', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Gestão do conhecimento (curso a ser dado e feito pelos servidores da SGIDOC)', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Eneagrama', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Necessidade de aperfeiçoamento.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('PROCESSO ADMINISTRATIVO DISCIPLINAR', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('PROCESSO ADMINISTRATIVO DISCIPLINAR', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Noções de espanhol', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Espanhol', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Desenvolver a capacidade de comunicação íntermediária em língua estrangeira', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Desenvolver a capacidade de comunicação íntermediária em língua estrangeira', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Noções de Inglês', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Inglês', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Desenvolver a capacidade de comunicação íntermediária em língua estrangeira', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Aprimorar a habilidade redacional do corpo técnico da Conleg, nos moldes do curso oferecido há alguns anos com o intrutor João Bosco.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('SIGA BRASIL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Treinamento no sistema SIAFI - Básico e Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Treinamento no sistema SICONV', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Parlamento digital Estudo de pesquisas relacionadas ao tema da cidadania digital, definição de conceitos da sociedade de redes e temas relacionados.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'COMUNICAÇÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Aprimorar o conhecimento do Orçamento e sua fiscalização', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Treinamento no SIGA BRASIL', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso de avaliação de políticas públicas, com ênfase em análise de dados: : analisar métodos de gestão de políticas públicas no Brasil, abordando métodos, objetivos, conceitos, tipos e crit. avaliação', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Curso avançado de avaliação de políticas públicas: analisar métodos de gestão de políticas públicas no Brasil, abordando métodos, objetivos, conceitos, tipos e critérios de avaliação.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'GESTÃO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Regimento Interno Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Aprimorar os conhecimentos sobre Regimento Interno do Corpo técnico da Conleg, para promover melhor embasamento das minutas produzidas', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Conhecer o processo legislativo e seus procedimentos formais', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Regimento Interno Avançado', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Necessidade de aperfeiçoamento.', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));
insert into treinamento (nome, ind_excluido, cod_area_conhecimento_id) values ('Técnica legislativa', false, (select cod_area_conhecimento from area_conhecimento where txt_descricao = 'DIREITO'));

-- Objetivo de treinamento
--select * from objetivo_treinamento 
insert into objetivo_treinamento (cod_objetivo_treinamento, nome, ind_excluido) values (default,'Atendimento ao usuário da área',false);
insert into objetivo_treinamento (cod_objetivo_treinamento, nome, ind_excluido) values (default,'Aperfeiçoamento das atividades da área',false);
insert into objetivo_treinamento (cod_objetivo_treinamento, nome, ind_excluido) values (default,'Manutenção das atividades da área',false);

-- Evento
-- select * from evento
insert into evento values (default,'Workshop', false);
insert into evento values (default,'Congresso', false);

-- Plano de capacitação
--SELECT * FROM plano_capacitacao
insert into plano_capacitacao values (default, 2019, true, false);

-- Nivel
insert into nivel (cod_nivel, nome) values (default,'Básico');
insert into nivel (cod_nivel, nome) values (default,'Intermediário');
insert into nivel (cod_nivel, nome) values (default,'Avançado');

-- Modalidade de treinamento
-- select * from modalidade_treinamento
insert into modalidade_treinamento (nome, ind_excluido) values ('Presencial', false);
insert into modalidade_treinamento (nome, ind_excluido) values ('A Distância', false);


-- Prioridade do treinamento
-- select * from prioridade
insert into prioridade (cod_prioridade, nome) values (default,'Baixa');
insert into prioridade (cod_prioridade, nome) values (default,'Média');
insert into prioridade (cod_prioridade, nome) values (default,'Alta');

